/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import Lodging from 'components/Lodging/Lodging';
import WidgetMSizeProgressChart from 'components/WidgetMSizeProgressChart/WidgetMSizeProgressChart';

const FlexboxTestWCustomCo = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `80px 40px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
  height: 'auto',
  width: 'fit-content',
});

const Frame48 = styled('div')({
  backgroundColor: `rgba(252, 4, 4, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  width: `385px`,
  height: `245px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Lodging1 = styled(Lodging)(({ theme }) => ({
  width: `330px`,
  height: `287px`,
  margin: `0px 0px 0px 60px`,
}));

const WidgetMSizeProgressC = styled(WidgetMSizeProgressChart)(({ theme }) => ({
  margin: `0px 0px 0px 60px`,
}));

function FlexboxTestWCustomComps(props) {
  return (
    <FlexboxTestWCustomCo>
      <Frame48></Frame48>
      <Lodging1 />
      <WidgetMSizeProgressC />
    </FlexboxTestWCustomCo>
  );
}

export default FlexboxTestWCustomComps;
