/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import useWeb3ResponsiveSize from './useWeb3ResponsiveSize';

//These are the possible values for the current variant. Use this to change the currentVariant dynamically.
//Please don't modify
const variantOptions = {
  ScreensDesktop: 'ScreensDesktop',
  ScreensTablet: 'ScreensTablet',
  ScreensMobile: 'ScreensMobile',
};

const useWeb3 = () => {
  const [currentVariant, setCurrentVariant] = React.useState(
    variantOptions['ScreensDesktop']
  );

  const breakpointsVariant = useWeb3ResponsiveSize();

  React.useEffect(() => {
    if (breakpointsVariant !== currentVariant) {
      setCurrentVariant(breakpointsVariant);
    }
  }, [breakpointsVariant]);

  let data = { currentVariant };

  let fns = { setCurrentVariant };
  return { data, fns };
};

export default useWeb3;
